import Navigation from "./components/navigation";
import "./globals.css";
import { Inter } from "next/font/google";
// import Footer from './components/footer/Footer';
import React from 'react';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Luxary Books",
  description: "Generated by Luxary Books",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation/>
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
